
const num =  11;

try {
    num = 12;
    
} catch(err){
    console.log(err);
}
console.log(num);

